number1=int(input("enter the 1st number"))
number2=int(input("enterb the 2nd number"))
sum=(number1+number2)
div=(number1/number2)
multi=(number1*number2)
sub=(number1-number2)
mod=(number1%number2)
rounded=(number1//number2)
print(sum)
print(div)
print(multi)
print(sub)
print(mod)
print(rounded)